---
title: "Assignment3"
author: "Kathleen Tran/Eric Almeida"
date: "3/6/2017"
output: pdf_document
---


```{r, echo=FALSE}
library(ggplot2)
library(curl)

gapminder_location<-curl(url = "https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv")
gapminder<-read.csv(gapminder_location)
```

```{r, echo=FALSE}
ggplot(gapminder, aes(x=lifeExp, y=gdpPercap))+geom_point()+scale_y_log10()+geom_smooth(method="lm")

ggplot(gapminder, aes(x=lifeExp, y=pop))+geom_point()+scale_y_log10()+geom_smooth(method="lm")
```

```{r, echo=FALSE}
ggplot(subset(gapminder, continent %in% c("Asia", "Africa")),
       aes(x=lifeExp,
           y=gdpPercap,
           color=continent))+geom_point()+geom_smooth()+ggtitle("Looking at Life Expectancy via GDP per Capita in Asia and Africa")

ggplot(subset(gapminder, continent %in% c("Americas", "Europe")),
       aes(x=lifeExp,
           y=gdpPercap,
           color=continent))+geom_point()+ggtitle("Looking at Life Expectancy via GDP per Capita in the 
          Americas and Europe")

ggplot(subset(gapminder, continent %in% c("Oceania", "Asia")),
       aes(x=lifeExp,
           y=gdpPercap,
           color=continent))+geom_point()+ggtitle("Looking at Life Expectancy via GDP per Capita in Oceania and Asia")
```

```{r, echo=FALSE}
ggplot(gapminder, aes(x=pop, y=gdpPercap, color=continent))+geom_bar(stat="identity")

ggplot(gapminder, aes(x=lifeExp, y=gdpPercap, color=continent))+geom_bar(stat="identity")

ggplot(gapminder, aes(x=lifeExp, y=year, color=continent))+geom_bar(stat="identity")

ggplot(subset(gapminder, continent %in% c("Asia", "Europe")),
       aes(x=lifeExp,
           y=gdpPercap,
           color=continent))+geom_bar(stat="identity")

ggplot(gapminder, aes(x=continent, y=pop, color=continent, by=country, fill=continent))+geom_bar(stat="identity")

ggplot(gapminder, aes(x=year, y=gdpPercap, fill=continent))+geom_bar(stat="identity", position=position_dodge())
```

